name: Platypus Papers
favicon: null
layout_spectrum: 0.7589605844113976
typography_spectrum: 0.6951561411842704
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.5898733073845506
  lightness: 0.6874857684597373
  saturation: 0.5731406768318266
  rhythmicContrast: 0.0944206565618515
purpose: []
