name: Platypus Papers
favicon: null
layout_spectrum: 0.61268
typography_spectrum: 0.5616
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#240c18'
    - '#815d67'
    - '#fffef8'
    - '#ffff0f'
    - '#d733c6'
  brandStrength: 0.25
  lightness: 0.875
  saturation: 0.625
  rhythmicContrast: 0.25
purpose: []
